### PR TITLE
Add duckdb-node trigger

### PR DESCRIPTION
**Pull request by Mause**

### CODE REVIEW

**Comment by Mause** [comment]
I don't have access to add a reviewer here, but can you have a look @carlopi ?

**Review by carlopi — APPROVED** [review]
Thanks for the needed refactoring, looks good to me (and in any case we will notice tonight on the first run if something happens to be off).

**Comment by carlopi** [comment]
Pinging also Mark as yet another set of eyes, but this is good to go in for me.

**Comment by Mytherin** [comment]
Thanks LGTM

**Pull request merged**
